USE master;
GO
DROP DATABASE IF EXISTS personsOrders;
GO
CREATE DATABASE personsOrders;
GO

USE personsOrders;

CREATE TABLE Persons(
ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
LastName VARCHAR(20) NOT NULL,
FirstName VARCHAR(20) NOT NULL,
Age INT
);

CREATE TABLE Orders(
OrderID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
OrderNumber INT NOT NULL,
PersonID INT NOT NULL
);

ALTER TABLE Orders ADD FOREIGN KEY (PersonID) REFERENCES Persons (ID);
